language: node_js

branches:
  only:
    - master

cache: yarn

node_js:
  - '8'
  - '6'
  - '4'

script: yarn run test

after_success:
  - yarn global add semantic-release
  - semantic-release pre && npm publish && semantic-release post
